import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'edge-rag-preferences';
const DEFAULT_PREFERENCES = {
  theme: 'dark',
  language: 'en',
};

const TRANSLATIONS = {
  en: {
    account: 'Account',
    accountActions: 'Account actions',
    accountCreated: 'Account created',
    activateSelectedFiles: 'Activate selected files',
    activeCorpus: 'Active corpus',
    answerStatus: 'Answer status',
    appLanguage: 'App language',
    appLanguageHelp: 'Arabic switches the interface to right-to-left layout.',
    appearance: 'Appearance',
    appearanceHelp: 'Choose the color mode for this browser.',
    arabic: 'Arabic',
    askAboutActiveText: 'Ask about the active text',
    askGroundedQuestion: 'Ask grounded question',
    assistant: 'Assistant',
    assistantDescription: 'General chat, files, and recent conversations',
    assistantFeature: 'General chat, multimodal file input, and session-based conversation history.',
    attachmentAnalyze: 'Please analyze the attached file(s).',
    attachFiles: 'Attach files',
    authHero: 'Offline grounded learning, in one workspace.',
    authHeroBody: 'Secure assistant chat, document-grounded study flows, and persistent sessions around your existing Jetson RAG backend.',
    awaitingAnswer: 'Awaiting answer',
    availableDocuments: 'Available documents',
    confirmDelete: 'Are you sure you want to delete "{name}"?',
    confirmPassword: 'Confirm password',
    createAccount: 'Create account',
    createAccountTitle: 'Create your account',
    createLocalAccountHelp: 'Create a local account for this workstation.',
    currentQuestion: 'Current question',
    dark: 'Dark',
    displayName: 'Display name',
    documents: 'Documents',
    dropFiles: 'Drop files to attach',
    dropFilesPlaceholder: 'Drop files here or keep typing...',
    email: 'Email',
    english: 'English',
    feedback: 'Feedback',
    filesCount: '{count} file(s)',
    generalChat: 'General chat',
    generatedQuestions: 'Generated questions',
    generateAndGrade: 'Generate and grade',
    generateQuestion: 'Generate question',
    gradeAnswer: 'Grade answer',
    groundedAnswerFound: 'Grounded answer found',
    groundedQa: 'Grounded Q&A',
    history: 'History',
    initial: 'U',
    initials: 'Initials',
    language: 'Language',
    light: 'Light',
    logout: 'Logout',
    messageAssistant: 'Message the assistant...',
    modelAnswer: 'Model answer',
    name: 'Name',
    newChat: 'New chat',
    noCorpusSelected: 'No corpus selected',
    noDocuments: 'No documents uploaded yet.',
    noGeneratedQuestion: 'No generated question yet.',
    noGeneratedQuestions: 'No generated questions yet.',
    noGrading: 'No grading result yet.',
    noGroundedAnswer: 'No grounded answer yet.',
    noQuestionStatus: 'No question status yet.',
    noSessions: 'No sessions yet.',
    noChatHistory: 'No chat history yet.',
    none: 'None',
    notAvailableInCorpus: 'Not available in corpus',
    notSet: 'Not set',
    nothingSelected: 'Nothing selected',
    password: 'Password',
    passwordsDoNotMatch: 'Passwords do not match.',
    pleaseWait: 'Please wait...',
    profile: 'Profile',
    profileLogoutHelp: 'This workspace is tied to your account. Logging out will keep your data on the server and end the current browser session.',
    question: 'Question',
    questionsAndStatus: 'Questions and answer status',
    ragStudio: 'RAG Studio',
    ragStudioDescription: 'Grounded documents and learning workflows',
    ragStudioFeature: 'Grounded answers, question generation, and grading over your active story corpus.',
    readAloud: 'Read aloud',
    readThisMessage: 'Read this message aloud',
    readingWorkflow: 'Reading workflow',
    recentChats: 'Recent chats',
    register: 'Register',
    removeFile: 'Remove {name}',
    repeatPassword: 'Repeat your password',
    restoringWorkspace: 'Restoring your workspace',
    score: 'Score',
    selectCorpusHelp: 'Select one or more uploaded files, then activate them as the current corpus.',
    send: 'Send',
    session: 'Session',
    settings: 'Settings',
    settingsSubtitle: 'Personalize display and language',
    signedIn: 'Signed in',
    signIn: 'Sign in',
    signInHelp: 'Sign in to continue into the assistant and RAG workspace.',
    startVoiceInput: 'Start voice input',
    stop: 'Stop',
    stopReading: 'Stop reading',
    stopReadingMessage: 'Stop reading this message',
    stopVoiceInput: 'Stop voice input',
    sources: 'Sources',
    speechUnsupported: 'Speech input is not supported in this browser',
    theme: 'Theme',
    thisQuestionNotAnswered: 'This generated question has not been answered yet.',
    typing: 'Typing...',
    analyzingPrompt: 'Analyzing prompt...',
    generating: 'Generating...',
    thinking: 'Thinking...',
    streaming: 'Streaming',
    tokens: 'tokens',
    elapsed: 'elapsed',
    stoppedByUser: 'Stopped by you.',
    modelThinking: 'Model is thinking...',
    modelReasoning: 'Model reasoning',
    welcomeHeading: 'Local assistant ready when you are.',
    welcomeBody: 'Ask anything, drop in an image, or paste a document to get started.',
    welcomeTipText: 'Tip: ask for code, a comparison, or a story.',
    welcomeTipImage: 'Tip: attach a PNG or JPEG to ask about an image.',
    welcomeTipStop: 'Tip: hit Stop any time to cancel a long generation.',
    selectedFiles: 'Selected files',
    rejectedFileType: 'Cannot attach "{name}" - unsupported file type.',
    rejectedFileSize: '"{name}" is larger than {limit} and was skipped.',
    tooManyFiles: 'You can attach at most {count} files per message.',
    viewImage: 'Open image {name}',
    unableToContinue: 'Unable to continue.',
    unknown: 'Unknown',
    uploadFile: 'Upload file',
    uploadingDocuments: 'Uploading documents',
    uploadingDocumentsHelp: 'Sending {count} file(s) to the backend.',
    processingUpload: 'Processing upload',
    processingUploadHelp: 'Extracting text and visuals from the uploaded file(s).',
    uploadComplete: 'Upload complete',
    user: 'User',
    useAtLeastEight: 'Use at least 8 characters',
    viewProfile: 'View profile',
    welcomeBack: 'Welcome back',
    you: 'You',
    yourAnswer: 'Your answer',
    yourFullName: 'Your full name',
    cachedChunksReady: 'Cached chunks ready',
    cachedChunksCount: '{count} cached chunks',
    needsChunking: 'Needs chunking',
    chunksReady: '{count} chunks indexed and ready for retrieval.',
    progress: 'Progress',
    activeNow: 'Active now',
    selectedDocumentsReady: '{count} selected file(s) are already chunked with {chunks} cached chunks ready to reuse.',
    selectedDocumentsPartialReady: '{ready} of {total} selected file(s) are already chunked. The rest will be prepared now.',
    preparingCorpus: 'Preparing corpus',
    loadingCachedChunks: 'Loading cached chunks',
    loadingCachedChunksHelp: 'Reusing chunk data for {count} selected file(s) before opening the combined index.',
    chunkingSelectedDocuments: 'Chunking selected documents',
    chunkingSelectedDocumentsHelp: 'Splitting the selected files into retrieval chunks for reuse and indexing.',
    buildingCombinedIndex: 'Building combined index',
    buildingCombinedIndexHelp: 'Combining all selected document chunks into one retrieval index for this session.',
    finalizingCorpus: 'Finalizing corpus',
    finalizingCorpusHelp: 'Saving the active corpus and refreshing the learning workspace.',
    corpusReady: 'Corpus ready',
    searchingActiveCorpus: 'Searching the active corpus',
    searchingActiveCorpusHelp: 'Retrieving relevant chunks and drafting a grounded answer from the selected document set.',
    generatingStudyQuestion: 'Generating a study question',
    generatingStudyQuestionHelp: 'Reviewing the active corpus, selecting useful passages, and drafting a new question.',
    gradingInProgress: 'Grading your answer',
    gradingInProgressHelp: 'Comparing your answer against the active corpus and preparing feedback.',
    groundedQuestionPlaceholder: 'Ask a question that must be answered only from the active document set.',
    generatedAnswerPlaceholder: 'Write your answer here. Paraphrasing is fine if the meaning is correct.',
    loginPasswordPlaceholder: 'Enter your password',
  },
  ar: {
    account: 'الحساب',
    accountActions: 'إجراءات الحساب',
    accountCreated: 'تاريخ إنشاء الحساب',
    activateSelectedFiles: 'تفعيل الملفات المحددة',
    activeCorpus: 'المجموعة النشطة',
    answerStatus: 'حالة الإجابة',
    appLanguage: 'لغة النظام',
    appLanguageHelp: 'العربية تحول الواجهة إلى اتجاه من اليمين إلى اليسار.',
    appearance: 'المظهر',
    appearanceHelp: 'اختر نمط الألوان لهذا المتصفح.',
    arabic: 'العربية',
    askAboutActiveText: 'اسأل عن النص النشط',
    askGroundedQuestion: 'اسأل سؤالا موثقا',
    assistant: 'المساعد',
    assistantDescription: 'محادثة عامة وملفات ومحادثات حديثة',
    assistantFeature: 'محادثة عامة وإدخال ملفات متعدد الوسائط وسجل محادثات حسب الجلسة.',
    attachmentAnalyze: 'يرجى تحليل الملفات المرفقة.',
    attachFiles: 'إرفاق ملفات',
    authHero: 'تعلم موثق دون اتصال في مساحة واحدة.',
    authHeroBody: 'محادثة مساعد آمنة، ومسارات دراسة موثقة بالمستندات، وجلسات محفوظة حول خادم Jetson RAG لديك.',
    awaitingAnswer: 'بانتظار الإجابة',
    availableDocuments: 'المستندات المتاحة',
    confirmDelete: 'هل أنت متأكد من حذف "{name}"؟',
    confirmPassword: 'تأكيد كلمة المرور',
    createAccount: 'إنشاء حساب',
    createAccountTitle: 'إنشاء حسابك',
    createLocalAccountHelp: 'أنشئ حسابا محليا لمحطة العمل هذه.',
    currentQuestion: 'السؤال الحالي',
    dark: 'داكن',
    displayName: 'اسم العرض',
    documents: 'المستندات',
    dropFiles: 'أفلت الملفات للإرفاق',
    dropFilesPlaceholder: 'أفلت الملفات هنا أو تابع الكتابة...',
    email: 'البريد الإلكتروني',
    english: 'الإنجليزية',
    feedback: 'الملاحظات',
    filesCount: '{count} ملف',
    generalChat: 'محادثة عامة',
    generatedQuestions: 'الأسئلة المولدة',
    generateAndGrade: 'توليد وتقييم',
    generateQuestion: 'توليد سؤال',
    gradeAnswer: 'تقييم الإجابة',
    groundedAnswerFound: 'تم العثور على إجابة موثقة',
    groundedQa: 'أسئلة وأجوبة موثقة',
    history: 'السجل',
    initial: 'م',
    initials: 'الأحرف الأولى',
    language: 'اللغة',
    light: 'فاتح',
    logout: 'تسجيل الخروج',
    messageAssistant: 'اكتب رسالة للمساعد...',
    modelAnswer: 'إجابة النموذج',
    name: 'الاسم',
    newChat: 'محادثة جديدة',
    noCorpusSelected: 'لا توجد مجموعة محددة',
    noDocuments: 'لم يتم رفع أي مستندات بعد.',
    noGeneratedQuestion: 'لا يوجد سؤال مولد بعد.',
    noGeneratedQuestions: 'لا توجد أسئلة مولدة بعد.',
    noGrading: 'لا توجد نتيجة تقييم بعد.',
    noGroundedAnswer: 'لا توجد إجابة موثقة بعد.',
    noQuestionStatus: 'لا توجد حالة أسئلة بعد.',
    noSessions: 'لا توجد جلسات بعد.',
    noChatHistory: 'لا يوجد سجل محادثة بعد.',
    none: 'لا شيء',
    notAvailableInCorpus: 'غير متاح في المجموعة',
    notSet: 'غير محدد',
    nothingSelected: 'لم يتم تحديد شيء',
    password: 'كلمة المرور',
    passwordsDoNotMatch: 'كلمتا المرور غير متطابقتين.',
    pleaseWait: 'يرجى الانتظار...',
    profile: 'الملف الشخصي',
    profileLogoutHelp: 'مساحة العمل مرتبطة بحسابك. تسجيل الخروج سيبقي بياناتك على الخادم وينهي جلسة المتصفح الحالية.',
    question: 'السؤال',
    questionsAndStatus: 'الأسئلة وحالة الإجابات',
    ragStudio: 'استوديو RAG',
    ragStudioDescription: 'مستندات موثقة ومسارات تعلم',
    ragStudioFeature: 'إجابات موثقة وتوليد أسئلة وتقييم فوق مجموعة القصص النشطة.',
    readAloud: 'قراءة بصوت عال',
    readThisMessage: 'قراءة هذه الرسالة بصوت عال',
    readingWorkflow: 'مسار القراءة',
    recentChats: 'المحادثات الحديثة',
    register: 'تسجيل',
    removeFile: 'إزالة {name}',
    repeatPassword: 'أعد كلمة المرور',
    restoringWorkspace: 'استعادة مساحة العمل',
    score: 'الدرجة',
    selectCorpusHelp: 'حدد ملفا مرفوعا أو أكثر، ثم فعله كمجموعة حالية.',
    send: 'إرسال',
    session: 'الجلسة',
    settings: 'الإعدادات',
    settingsSubtitle: 'تخصيص العرض واللغة',
    signedIn: 'تم تسجيل الدخول',
    signIn: 'تسجيل الدخول',
    signInHelp: 'سجل الدخول للمتابعة إلى المساعد ومساحة RAG.',
    startVoiceInput: 'بدء الإدخال الصوتي',
    stop: 'إيقاف',
    stopReading: 'إيقاف القراءة',
    stopReadingMessage: 'إيقاف قراءة هذه الرسالة',
    stopVoiceInput: 'إيقاف الإدخال الصوتي',
    sources: 'المصادر',
    speechUnsupported: 'الإدخال الصوتي غير مدعوم في هذا المتصفح',
    theme: 'النمط',
    thisQuestionNotAnswered: 'لم تتم الإجابة عن هذا السؤال المولد بعد.',
    typing: 'يكتب...',
    analyzingPrompt: 'جارٍ تحليل الطلب...',
    generating: 'جارٍ التوليد...',
    thinking: 'يفكر...',
    streaming: 'بث الإجابة',
    tokens: 'رموز',
    elapsed: 'مضى',
    stoppedByUser: 'أوقفت العملية.',
    modelThinking: 'النموذج يفكر...',
    modelReasoning: 'تفكير النموذج',
    welcomeHeading: 'المساعد المحلي جاهز عندما تكون مستعدًا.',
    welcomeBody: 'اسأل أي شيء، أرفق صورة، أو الصق مستندًا للبدء.',
    welcomeTipText: 'نصيحة: اطلب رمزًا برمجيًا أو مقارنة أو قصة.',
    welcomeTipImage: 'نصيحة: أرفق صورة PNG أو JPEG لطرح أسئلة عنها.',
    welcomeTipStop: 'نصيحة: اضغط إيقاف لإلغاء التوليد في أي لحظة.',
    selectedFiles: 'الملفات المختارة',
    rejectedFileType: 'لا يمكن إرفاق "{name}" - نوع غير مدعوم.',
    rejectedFileSize: 'حجم "{name}" أكبر من {limit} ولم يتم إضافته.',
    tooManyFiles: 'يمكن إرفاق {count} ملفات كحد أقصى لكل رسالة.',
    viewImage: 'فتح الصورة {name}',
    unableToContinue: 'تعذر المتابعة.',
    unknown: 'غير معروف',
    uploadFile: 'رفع ملف',
    uploadingDocuments: 'جار رفع المستندات',
    uploadingDocumentsHelp: 'جار إرسال {count} ملف/ملفات إلى الخادم.',
    processingUpload: 'جار معالجة الرفع',
    processingUploadHelp: 'جار استخراج النصوص والعناصر البصرية من الملفات المرفوعة.',
    uploadComplete: 'اكتمل الرفع',
    user: 'مستخدم',
    useAtLeastEight: 'استخدم 8 أحرف على الأقل',
    viewProfile: 'عرض الملف الشخصي',
    welcomeBack: 'مرحبا بعودتك',
    you: 'أنت',
    yourAnswer: 'إجابتك',
    yourFullName: 'اسمك الكامل',
    cachedChunksReady: 'المقاطع المخبأة جاهزة',
    cachedChunksCount: '{count} مقاطع مخبأة',
    needsChunking: 'يحتاج إلى تقسيم',
    chunksReady: '{count} مقاطع مفهرسة وجاهزة للاسترجاع.',
    progress: 'التقدم',
    activeNow: 'نشط الآن',
    selectedDocumentsReady: '{count} ملفا محددا مقسم بالفعل وبداخله {chunks} مقاطع مخبأة جاهزة لإعادة الاستخدام.',
    selectedDocumentsPartialReady: '{ready} من أصل {total} ملفات محددة مقسمة بالفعل وسيتم تجهيز البقية الآن.',
    preparingCorpus: 'جار تحضير المجموعة',
    loadingCachedChunks: 'جار تحميل المقاطع المخبأة',
    loadingCachedChunksHelp: 'تتم إعادة استخدام بيانات المقاطع للملفات المحددة قبل فتح الفهرس المدمج.',
    chunkingSelectedDocuments: 'جار تقسيم الملفات المحددة',
    chunkingSelectedDocumentsHelp: 'يتم تقسيم الملفات المحددة إلى مقاطع قابلة للاسترجاع لحفظها وإعادة استخدامها.',
    buildingCombinedIndex: 'جار بناء الفهرس المدمج',
    buildingCombinedIndexHelp: 'يتم دمج مقاطع كل الملفات المحددة في فهرس استرجاع واحد لهذه الجلسة.',
    finalizingCorpus: 'جار إنهاء المجموعة',
    finalizingCorpusHelp: 'يتم حفظ المجموعة النشطة وتحديث مساحة التعلم.',
    corpusReady: 'المجموعة جاهزة',
    searchingActiveCorpus: 'جار البحث في المجموعة النشطة',
    searchingActiveCorpusHelp: 'يتم استرجاع المقاطع ذات الصلة وصياغة إجابة موثقة من الملفات المحددة.',
    generatingStudyQuestion: 'جار توليد سؤال دراسي',
    generatingStudyQuestionHelp: 'تتم مراجعة المجموعة النشطة واختيار المقاطع المفيدة وصياغة سؤال جديد.',
    gradingInProgress: 'جار تقييم إجابتك',
    gradingInProgressHelp: 'تتم مقارنة إجابتك مع المجموعة النشطة وإعداد الملاحظات.',
    groundedQuestionPlaceholder: 'اسأل سؤالا يجب أن تتم الإجابة عنه فقط من مجموعة المستندات النشطة.',
    generatedAnswerPlaceholder: 'اكتب إجابتك هنا. لا بأس بإعادة الصياغة إذا كان المعنى صحيحا.',
    loginPasswordPlaceholder: 'أدخل كلمة المرور',
  },
};

function loadPreferences() {
  try {
    const parsed = JSON.parse(window.localStorage.getItem(STORAGE_KEY) || '{}');
    return {
      theme: parsed.theme === 'light' ? 'light' : 'dark',
      language: parsed.language === 'ar' ? 'ar' : 'en',
    };
  } catch (_error) {
    return DEFAULT_PREFERENCES;
  }
}

function formatTemplate(template, values) {
  return String(template).replace(/\{(\w+)\}/g, (_match, key) => values?.[key] ?? '');
}

const PreferencesContext = createContext(null);

export function PreferencesProvider({ children }) {
  const [preferences, setPreferences] = useState(() => loadPreferences());

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(preferences));
    document.documentElement.dataset.theme = preferences.theme;
    document.documentElement.lang = preferences.language === 'ar' ? 'ar' : 'en';
    document.documentElement.dir = preferences.language === 'ar' ? 'rtl' : 'ltr';
  }, [preferences]);

  const value = useMemo(() => {
    const language = preferences.language;
    const strings = TRANSLATIONS[language] || TRANSLATIONS.en;
    return {
      ...preferences,
      dir: language === 'ar' ? 'rtl' : 'ltr',
      locale: language === 'ar' ? 'ar-SA' : 'en-US',
      speechLanguage: language === 'ar' ? 'ar-SA' : 'en-US',
      setTheme: (theme) => {
        setPreferences((current) => ({ ...current, theme: theme === 'light' ? 'light' : 'dark' }));
      },
      setLanguage: (nextLanguage) => {
        setPreferences((current) => ({ ...current, language: nextLanguage === 'ar' ? 'ar' : 'en' }));
      },
      t: (key, values) => formatTemplate(strings[key] || TRANSLATIONS.en[key] || key, values),
    };
  }, [preferences]);

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function usePreferences() {
  const value = useContext(PreferencesContext);
  if (!value) {
    throw new Error('usePreferences must be used inside PreferencesProvider.');
  }
  return value;
}
